version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9092" # Yerel makineden erişim için: dışarıdan 9094, içeride 9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:14
    container_name: cdr_postgres_main
    environment:
      POSTGRES_DB: cdr_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cdr-processor:
    build:
      context: ./cdr-processor
    container_name: cdr-processor
    depends_on:
      - kafka
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://cdr_postgres_main:5432/cdr_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  cdr-reporter:
    build:
      context: ./cdr-reporter
    container_name: cdr-reporter
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cdr_postgres_main:5432/cdr_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  cdr-generator:
    build:
      context: ./cdr-generator
    container_name: cdr-generator
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_TOPIC: cdr-raw-topic
      GEN_RATE_PER_SEC: "0.2" # <--- Burası 3'ten 0.2'ye değiştirildi!
    restart: unless-stopped

volumes:
  pgdata:
